sudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install codecov pytest-cov"
  - python setup.py build_ext --inplace
script:
  - make lint
  - py.test spacegraphcats search --cov=.
  - scripts/test-search-changes.sh

after_success:
  - codecov
