sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install codecov pytest-cov"
script: py.test --cov=.
after_success:
  - codecov
