sudo: required
dist: trusty
language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install codecov pytest-cov"
  - python setup.py build_ext --inplace
script: py.test spacegraphcats --cov=.
after_success:
  - codecov
